steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/testing-node/$PROJECT_ID:$REVISION_ID', 'node' ]
images:
- 'eu.gcr.io/testing-node/$PROJECT_ID:$REVISION_ID'
timeout: "1200s"
