apiVersion: skaffold/v1
kind: Config
metadata:
  name: denis-project
build:
  artifacts:
  - image: denissweat/testing-node
    context: node
    sync:
      manual:
      - src: 'src/*.js'
        dest: .
        strip: src/