apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello.test
    http: &http_rules
      paths:
      - paths:
        backend:
          serviceName: node-cluster-ip-service
          servicePort: 3050
  - host: hello.info
    http: *http_rules
  - host: app.hello.test
    http: *http_rules

